### ISSUE TITLE
Error: HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1

### ISSUE THREAD

**Issue by cburgdorfer** [originallyus/node-red-contrib-better-sonos#26]
Hi all,

I am using "Sonos Control" but it seems I am getting the following errors for the respective commands:

```
"Error: HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1#Pause""
"Error: HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1#Next""
"Error: HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1#Previous""
```

- Play
- Stop
- Mute
- Unmute
- Volume Up
- Volume Down

seem to all work. Just the others throw error messages:

```
22 Sep 20:49:46 - [error] [better-sonos-control:7997c9b0.f7e378] Error: HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1#Next"
Error: HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1#Next"
    at Request._callback (/home/pi/.node-red/node_modules/sonos/lib/sonos.js:216:23)
    at Request.self.callback (/home/pi/.node-red/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/pi/.node-red/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/pi/.node-red/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```

Do you have any ideas what the problem could be and how I can solve it?

Thanks!

Christoph

**Comment by matthias-burgfried** [comment]
Same here.

**Comment by simzdk** [comment]
Same error here.
