### ISSUE TITLE
Join stops NodeRed

### ISSUE THREAD

**Issue by andreapx** [originallyus/node-red-contrib-better-sonos#27]
After pushing the Join command, NodeRed stop with this errors:
`Found Sonos device B8-E9-37-5F-A7-72:6 at 192.168.20.47
1 Nov 18:47:57 - [red] Uncaught Exception:
1 Nov 18:47:57 - TypeError: Cannot read property 'find' of null
    at getTopology (/home/pi/.node-red/node_modules/sonos/lib/sonos.js:619:31)
    at /home/pi/.node-red/node_modules/sonos/lib/sonos.js:1077:7
    at Parser.<anonymous> (/home/pi/.node-red/node_modules/xml2js/lib/parser.js:303:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onclosetag (/home/pi/.node-red/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/home/pi/.node-red/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/pi/.node-red/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/home/pi/.node-red/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/home/pi/.node-red/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/home/pi/.node-red/node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (/home/pi/.node-red/node_modules/xml2js/lib/parser.js:5:59)
    at Object.exports.parseString (/home/pi/.node-red/node_modules/xml2js/lib/parser.js:354:19)
    at Request._callback (/home/pi/.node-red/node_modules/sonos/lib/sonos.js:1062:12)
    at Request.self.callback (/home/pi/.node-red/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)`

This is my sketch:
`[{"id":"aaeabd.e374654","type":"better-sonos-control","z":"ecc2de2b.8c965","confignode":"164fdcf2.cb59bb","name":"","mode":"","track":"","volume":"","volume_value":"","x":480,"y":160,"wires":[]},{"id":"ca4a84ea.beff28","type":"inject","z":"ecc2de2b.8c965","name":"","topic":"Bathroom","payload":"join","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":290,"y":160,"wires":[["aaeabd.e374654"]]},{"id":"164fdcf2.cb59bb","type":"better-sonos-config","z":"","name":"Bedroom","serialnum":"B8-E9-37-5F-A7-72:6","ipaddress":""}]`

Where could the problem be?
Andrea

**Comment by 80AAFF** [comment]
After an upgrade Sonos does no longer support the url http://{sonos'ip}:1400/status/topology which this application relies on

**Comment by evazzoler** [comment]
How to fix it? My nodered stops, too.

**Comment by andreapx** [comment]
> After an upgrade Sonos does no longer support the url http://{sonos'ip}:1400/status/topology which this application relies on

@80AAFF  Ok, thanks for the info
