### ISSUE TITLE
Error: HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1#Seek"

### ISSUE THREAD

**Issue by trp79** [originallyus/node-red-contrib-better-sonos#29]
Hi, 
When using a Sonos Queue node with a https reference to localhost (using the IP of the host) I get below error. If I point to a http address on the internet for playing a MP3 doorbell file it works fine - I would however like to have it locally to minimize latency and not to be dependent on internet connection. I can access https://1.2.3.4:8123/local/doorbell/doorbell1.mp3 in the browser and the MP3 doorbell plays fine as expected.

Hope you can help. Thanks a lot :)

KR
Torben

18 Dec 12:28:40 - [info] [better-sonos-queue:33a738af.d038b8] Direct play URI: https://1.2.3.4:8123/local/doorbell/doorbell1.mp3
18 Dec 12:28:40 - [error] [better-sonos-queue:33a738af.d038b8] Error: HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1#Seek"
Error: HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1#Seek"
    at Request._callback (/config/node-red/node_modules/sonos/lib/sonos.js:216:23)
    at Request.self.callback (/config/node-red/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/config/node-red/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/config/node-red/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
18 Dec 12:44:16 - [info] Stopping flows

**Comment by arachnida** [comment]
I have the same problem, but could find a workaround for it; I queue the file first and then after a delay of 2s I start the queue using a control node.

**Comment by Daigaard** [comment]
This worked for me also, great thanks.
