### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by vworp** [originallyus/node-red-contrib-better-sonos#3]
Getting a crash.

22 Oct 16:09:02 - [red] Uncaught Exception:
22 Oct 16:09:02 - TypeError: Cannot read property 'destroy' of null
    at C:\Users\max\.node-red\node_modules\node-red-contrib-better-sonos\sonos\SonosHelper.js:74:27
    at C:\Users\max\.node-red\node_modules\sonos\lib\sonos.js:795:7
    at Parser.<anonymous> (C:\Users\max\.node-red\node_modules\sonos\node_modules\xml2js\lib\xml2js.js:489:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Object.onclosetag (C:\Users\max\.node-red\node_modules\sonos\node_modules\xml2js\lib\xml2js.js:447:26)
    at emit (C:\Users\max\.node-red\node_modules\sax\lib\sax.js:624:35)
    at emitNode (C:\Users\max\.node-red\node_modules\sax\lib\sax.js:629:5)
    at closeTag (C:\Users\max\.node-red\node_modules\sax\lib\sax.js:889:7)
    at Object.write (C:\Users\max\.node-red\node_modules\sax\lib\sax.js:1436:13)

**Comment by torinnguyen** [comment]
Fixed in version 0.1.6

**Comment by vworp** [comment]
Got a new one.



22 Oct 17:27:04 - ReferenceError: result is not defined
    at C:\Users\max\.node-red\node_modules\node-red-contrib-better-sonos\sonos\sonos-control.js:173:40
    at C:\Users\max\.node-red\node_modules\sonos\lib\sonos.js:312:5
    at C:\Users\max\.node-red\node_modules\sonos\lib\sonos.js:149:14
    at Parser.<anonymous> (C:\Users\max\.node-red\node_modules\sonos\node_modules\xml2js\lib\xml2js.js:489:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Object.onclosetag (C:\Users\max\.node-red\node_modules\sonos\node_modules\xml2js\lib\xml2js.js:447:26)
    at emit (C:\Users\max\.node-red\node_modules\sax\lib\sax.js:624:35)
    at emitNode (C:\Users\max\.node-red\node_modules\sax\lib\sax.js:629:5)
    at closeTag (C:\Users\max\.node-red\node_modules\sax\lib\sax.js:889:7)

**Comment by torinnguyen** [comment]
It is fixed.
